// netlify/functions/admin-action.js — CommonJS format
const { createClient } = require('@supabase/supabase-js');

const supabase = () => createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_KEY
);

const SEED = [
  { slug:'paul-rand', category_slug:'llegendes', name:'Paul Rand', tagline_ca:'El pare del branding corporatiu modern', tagline_es:'El padre del branding corporativo moderno', period:'1914–1996', origin:'Nova York, EUA', portrait_url:'https://upload.wikimedia.org/wikipedia/commons/b/bb/Paul_rand_loc.jpg', bio_ca:"Arquitecte del disseny gràfic americà del segle XX, Rand va transformar la publicitat en art. El seu mètode: identificar l'essència conceptual abans de traçar una sola línia.", bio_es:"Arquitecto del diseño gráfico americano del siglo XX, Rand transformó la publicidad en arte. Su método: identificar la esencia conceptual antes de trazar una sola línea.", style:['Geometria simple i directa','Paletes reduïdes d\'alt contrast','Síntesi conceptual extrema','Equilibri entre lúdic i corporatiu','Tipografia integrada amb la imatge'], techniques:['Abstracció simbòlica del concepte','Construcció per formes bàsiques','Color com a vehicle emocional','Exploració de variacions fins a l\'essència','Lettering personalitzat com a logotip'], principles:[{name:'La forma segueix la funció',desc:'Cada element ha de guanyar-se el lloc amb una raó comunicativa clara.'},{name:'Síntesi màxima',desc:'El millor logotip no pot perdre res sense perdre significat.'},{name:'Joc intel·ligent',desc:"La playfulness no és oposada a la serietat."}], works:[{title:'IBM (1956)',desc:'Identitat ratllada que comunicava tecnologia i ordre'},{title:'ABC Television (1962)',desc:'Cercle negre. Tres lletres. Recognoscible a qualsevol escala'},{title:'UPS (1961)',desc:'Escut amb llaç: protecció i confiança en un gest gràfic'}], lesson_ca:"Abans de dissenyar, troba l'essència del problema. La simplicitat és la destil·lació màxima del significat.", lesson_es:"Antes de diseñar, encuentra la esencia del problema. La simplicidad es la destilación máxima del significado.", sources:["Paul Rand: A Designer's Art (1985)",'www.paul-rand.com'], video_id:'YqQx75OPRa0', links:[{label:'paul-rand.com',url:'https://www.paul-rand.com',icon:'🌐'},{label:'MoMA',url:'https://www.moma.org/artists/4760',icon:'🎨'}], sort_order:1 },
  { slug:'milton-glaser', category_slug:'llegendes', name:'Milton Glaser', tagline_ca:'El comunicador més popular del segle XX', tagline_es:'El comunicador más popular del siglo XX', period:'1929–2020', origin:'Nova York, EUA', portrait_url:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Milton_Glaser_at_Cooper_Hewitt%2C_Smithsonian_Design_Museum.jpg/330px-Milton_Glaser_at_Cooper_Hewitt%2C_Smithsonian_Design_Museum.jpg', bio_ca:"Cofundador de la revista New York i creador de l'I love NY, Glaser entenia el disseny com a comunicació popular.", bio_es:"Cofundador de la revista New York y creador del I love NY, Glaser entendía el diseño como comunicación popular.", style:['Línies fluïdes i orgàniques','Colors plans i vibrants','Humor visual i ironia'], techniques:['Esbós a mà com a punt de partida','Metàfora visual directa','Color simbòlic, no decoratiu'], principles:[{name:'Claredat emocional',desc:"Un disseny s'ha de sentir abans d'entendre's."},{name:'Democràcia visual',desc:"El gran disseny no exigeix formació per ser apreciat."},{name:"L'error com a oportunitat",desc:'Els accidents revelen camins que la planificació mai no trobaria.'}], works:[{title:"I love NY (1977)",desc:'El logotip més copiat de la història'},{title:'Bob Dylan Poster (1966)',desc:"Silueta psicodèlica, icona d'una generació"},{title:'Revista New York',desc:'Va redefinir el disseny editorial americà'}], lesson_ca:"El disseny més efectiu sempre té una idea central irresistible. Abans del software, troba la metàfora perfecta.", lesson_es:"El diseño más efectivo siempre tiene una idea central irresistible.", sources:['Milton Glaser: Graphic Design (1973)','www.miltonglaser.com'], video_id:'D7OEVCroTi4', links:[{label:'miltonglaser.com',url:'https://www.miltonglaser.com',icon:'🌐'}], sort_order:2 },
  { slug:'saul-bass', category_slug:'llegendes', name:'Saul Bass', tagline_ca:'El mestre dels títols cinematogràfics', tagline_es:'El maestro de los títulos cinematográficos', period:'1920–1996', origin:'Nova York, EUA', portrait_url:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Saul_Bass_gesturing%2C_RIT_NandE_Vol11Num19_1979_May10_Complete.jpg/330px-Saul_Bass_gesturing%2C_RIT_NandE_Vol11Num19_1979_May10_Complete.jpg', bio_ca:"Bass va revolucionar la relació cinema-disseny. La seva col·laboració amb Hitchcock va canviar el vocabulari del disseny en moviment.", bio_es:"Bass revolucionó la relación cine-diseño. Su colaboración con Hitchcock cambió el vocabulario del diseño en movimiento.", style:['Formes geomètriques fragmentades','Moviment implícit en composició estàtica','Tensió dramàtica com a recurs estètic'], techniques:['Col·latge analògic de paper retallat','Reducció a símbol essencial','Ritme visual sincronitzat amb música'], principles:[{name:'El disseny com a narrativa',desc:'Cada imatge ha de generar anticipació emocional.'},{name:'La restricció allibera',desc:'Les formes simples creen més tensió quan estan ben col·locades.'},{name:'El moviment com a significat',desc:"El bon disseny fa que l'ull es mogui amb intenció pròpia."}], works:[{title:'Vèrtigo (1958)',desc:'Espirals hipnòtiques que defineixen la psicologia del film'},{title:'Psicosi (1960)',desc:'Línies fragmentades que generen angoixa'},{title:'AT&T Logo (1969)',desc:"Una de les identitats corporatives més longeues"}], lesson_ca:"Dissenya l'estat emocional abans que l'objecte visual.", lesson_es:"Diseña el estado emocional antes que el objeto visual.", sources:['Saul Bass: A Life in Film and Design (2011)','www.saulbass.net'], video_id:'IXB3hFDBWUQ', links:[{label:'saulbass.net',url:'https://www.saulbass.net',icon:'🌐'},{label:'Art of the Title',url:'https://www.artofthetitle.com/designer/saul-bass/',icon:'🎬'}], sort_order:3 },
  { slug:'massimo-vignelli', category_slug:'llegendes', name:'Massimo Vignelli', tagline_ca:'El saci sacerdot del minimalisme funcional', tagline_es:'El sumo sacerdote del minimalismo funcional', period:'1931–2014', origin:'Milà, Itàlia', portrait_url:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Massimo_Vignelli_2.jpg/330px-Massimo_Vignelli_2.jpg', bio_ca:"Per a Vignelli el disseny era un sistema, no una decoració. El seu treball al metro de Nova York va demostrar que bellesa i eficiència són inseparables.", bio_es:"Para Vignelli el diseño era un sistema, no una decoración. Su trabajo en el metro de Nueva York demostró que belleza y eficiencia son inseparables.", style:['Blanc, negre i un sol accent','Tipografia Helvetica gairebé exclusiva','Absència total d\'ornamentació'], techniques:['Retícula modular com a base sagrada','Paleta de 6 colors màxim','Família tipogràfica única per identitat'], principles:[{name:'Elimina sense pietat',desc:'Un element que no comunica activament està contaminant.'},{name:"La retícula és llibertat",desc:"Només amb l'ordre establert apareix la veritable expressió."},{name:'El disseny dura',desc:'Un bon sistema ha de funcionar igual el 1970 que el 2024.'}], works:[{title:'NYC Subway Map (1972)',desc:'Claredat funcional sobre realisme geogràfic'},{title:'Knoll Graphics',desc:'Elegància tipogràfica que va definir el modernisme'},{title:'American Airlines (1967)',desc:"La doble A en Helvetica"}], lesson_ca:"Abans d'afegir qualsevol element: què passaria si no hi fos?", lesson_es:"Antes de añadir cualquier elemento: ¿qué pasaría si no estuviera?", sources:['Vignelli Canon (PDF gratuït)','vignellicenter.rit.edu'], video_id:'LuS1SxBr1SE', links:[{label:'Vignelli Center',url:'https://vignellicenter.rit.edu',icon:'🌐'}], sort_order:4 },
  { slug:'herb-lubalin', category_slug:'llegendes', name:'Herb Lubalin', tagline_ca:'El revolucionari de la tipografia expressiva', tagline_es:'El revolucionario de la tipografía expresiva', period:'1918–1981', origin:'Nova York, EUA', portrait_url:'https://upload.wikimedia.org/wikipedia/en/e/e9/Lubalinlogo.jpg', bio_ca:"Lubalin va convertir la tipografia en imatge. Els seus logos on les lletres es fusionen van anticipar el disseny tipogràfic conceptual contemporani per dues dècades.", bio_es:"Lubalin convirtió la tipografía en imagen. Sus logos donde las letras se fusionan anticiparon el diseño tipográfico conceptual contemporáneo.", style:['Lletres que es toquen, superposen o fusionen','Espaiat negatiu com a eina','Tipografia com a il·lustració'], techniques:['Kern negatiu portat al límit','Lligadures tipogràfiques a mida','Lettering com a logotip'], principles:[{name:'La lletra té cos',desc:'La tipografia té pes, textura, moviment i emoció.'},{name:"L'espai negatiu parla",desc:'El que hi ha entre les lletres comunica tant com elles mateixes.'},{name:'Transgressió amb propòsit',desc:'Les normes existeixen per saber quan trencar-les.'}], works:[{title:'ITC Avant Garde (1970)',desc:'Tipografia geomètrica amb lligadures icòniques'},{title:'"Mother & Child" (1965)',desc:"La & com a úter: síntesi perfecta"},{title:'U&lc Magazine',desc:'Va redefinir el disseny editorial tipogràfic'}], lesson_ca:"Tracta cada lletra com una forma, no com un signe.", lesson_es:"Trata cada letra como una forma, no como un signo.", sources:["Herb Lubalin: Art Director (1985)",'lubalincenter.cooper.edu'], video_id:'ZUepzRz8qO0', links:[{label:'Lubalin Center',url:'https://lubalincenter.cooper.edu',icon:'🌐'}], sort_order:5 },
  { slug:'david-carson', category_slug:'llegendes', name:'David Carson', tagline_ca:'El pare del disseny tipogràfic grunge', tagline_es:'El padre del diseño tipográfico grunge', period:'1955–present', origin:'Califòrnia, EUA', portrait_url:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/20190513-BT-Dus-David_Carson-NP.jpg/330px-20190513-BT-Dus-David_Carson-NP.jpg', bio_ca:"Carson va subvertir totes les normes tipogràfiques a Ray Gun i va demostrar que la il·legibilitat pot ser la forma més poderosa de comunicar actitud.", bio_es:"Carson subvirtió todas las normas tipográficas en Ray Gun demostrando que la ilegibilidad puede ser la forma más poderosa de comunicar actitud.", style:['Tipografia fragmentada, girada i superposada','Caos ordenat per intuïció','Emoció visceral sobre claredat racional'], techniques:['Fotocomposició analògica i errors deliberats','Capes de text a distintes opacitats','Glitch i escàner com a eines'], principles:[{name:"Il·legibilitat no és mala comunicació",desc:'Una pàgina que transmet energia compleix la seva funció.'},{name:"L'accident és informació",desc:'Els errors tècnics revelen veritats que el control no assoleix.'},{name:"L'actitud es dissenya",desc:"L'estil tipogràfic pot ser tan poderós com una fotografia."}], works:[{title:'Ray Gun Magazine (1992)',desc:"Laboratori que va definir l'estètica del rock alternatiu dels 90"},{title:'Beach Culture Magazine',desc:'Més de 150 premis internacionals'},{title:'End of Print',desc:'La referència del disseny gràfic transgressor'}], lesson_ca:"Un cop dominis totes les normes, pregunta't què comunica trencar-les.", lesson_es:"Una vez que domines todas las reglas, pregúntate qué comunica romperlas.", sources:['The End of Print (1995)','www.davidcarsondesign.com'], video_id:'MsxFMGXUqWw', links:[{label:'davidcarsondesign.com',url:'https://www.davidcarsondesign.com',icon:'🌐'}], sort_order:6 },
  { slug:'neville-brody', category_slug:'llegendes', name:'Neville Brody', tagline_ca:'El dissenyador que va donar forma visual al punk i el pop', tagline_es:'El diseñador que dio forma visual al punk y el pop', period:'1957–present', origin:'Londres, R.U.', portrait_url:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Neville_Brody_TYPO_SF_2012.jpg/330px-Neville_Brody_TYPO_SF_2012.jpg', bio_ca:"Brody va transformar el disseny editorial en acte cultural. Les seves portades per a The Face van convertir les revistes en objectes de culte.", bio_es:"Brody transformó el diseño editorial en acto cultural. Sus portadas para The Face convirtieron las revistas en objetos de culto.", style:['Tipografies pròpies constructivistes','Tensió geomètrica en la composició','Alt contrast tipogràfic'], techniques:['Tipografies pròpies per a cada projecte','Retícula trencada amb norma interna','Lettering com a marca editorial'], principles:[{name:'El medi és el missatge',desc:'La revista no conté el missatge cultural, ho és.'},{name:'Tipografia com a veu',desc:"L'elecció tipogràfica comunica actitud abans de llegir."},{name:'Dissenyar contra el temps',desc:'El millor treball captura un moment cultural.'}], works:[{title:'The Face Magazine (1981)',desc:'El disseny editorial més influent dels anys 80'},{title:'Arena Magazine',desc:"Estètica masculina que va definir el luxe editorial anglès"},{title:'Fuse Magazine',desc:'Investigació tipogràfica experimental'}], lesson_ca:"El disseny editorial no és decoració; és la capa cultural que dóna significat.", lesson_es:"El diseño editorial no es decoración; es la capa cultural que da significado.", sources:['The Graphic Language of Neville Brody (1988)','www.researchstudios.com'], video_id:'aP-d_-eMObY', links:[{label:'Research Studios',url:'https://www.researchstudios.com',icon:'🌐'}], sort_order:7 },
  { slug:'muriel-cooper', category_slug:'llegendes', name:'Muriel Cooper', tagline_ca:'La pionera del disseny digital com a llenguatge', tagline_es:'La pionera del diseño digital como lenguaje', period:'1925–1994', origin:'Massachusetts, EUA', portrait_url:null, bio_ca:"Primera directora d'art del MIT Press, cofundadora del Visible Language Workshop. Va ser la primera a plantejar que la pantalla digital té les seves pròpies dimensions expressives.", bio_es:"Primera directora de arte del MIT Press. Fue la primera en plantear que la pantalla digital tiene sus propias dimensiones expresivas.", style:['Minimalisme informacional rigorós','Tipografia com a arquitectura de dades','Abstracció funcional'], techniques:['Retícula adaptativa','Tipografia multi-escala simultània','Interactivitat com a variable de disseny'], principles:[{name:'La pantalla no és un paper',desc:'El disseny digital té temps, interacció i profunditat pròpies.'},{name:'Informació com a forma',desc:'Les dades ben organitzades tenen la mateixa bellesa que la geometria.'},{name:'El disseny anticipa el futur',desc:'Els millors dissenyadors creen el vocabulari del demà.'}], works:[{title:'The Bauhaus (MIT Press, 1969)',desc:"Referència mundial del llibre d'art"},{title:'Visible Language Workshop',desc:'Va anticipar les interfícies digitals'},{title:'Information Landscapes (1994)',desc:'Primera tipografia 3D interactiva'}], lesson_ca:"Quan dissenyes per a pantalla, pensa en capes de temps.", lesson_es:"Cuando diseñes para pantalla, piensa en capas de tiempo.", sources:['MIT Press 50 Years','Visible Language Workshop Archive'], video_id:null, links:[{label:'MIT Media Lab',url:'https://www.media.mit.edu',icon:'🌐'}], sort_order:8 },
  { slug:'paula-scher', category_slug:'branding', name:'Paula Scher', tagline_ca:"La mestra de l'impacte tipogràfic massiu", tagline_es:'La maestra del impacto tipográfico masivo', period:'1948–present', origin:'Washington D.C., EUA', portrait_url:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Paula_Scher_interview_OnCreativity.jpg/330px-Paula_Scher_interview_OnCreativity.jpg', bio_ca:"Sòcia de Pentagram, Scher va desenvolupar el concepte de tipografia com a arquitectura urbana.", bio_es:"Socia de Pentagram, Scher desarrolló el concepto de tipografía como arquitectura urbana.", style:['Tipografia com a imatge principal absoluta','Color saturat i pla','Energia populista i urbana'], techniques:['Cartografies tipogràfiques pintades a mà','Identitats modulars amb variacions infinites','Color com a firma d\'identitat'], principles:[{name:'La tipografia crida',desc:'Quan la tipografia és poderosa, la lletra és la imatge completa.'},{name:'Un sistema mai és rígid',desc:'Una identitat forta permet variacions infinites.'},{name:'Dissenya per al carrer',desc:"El millor disseny funciona a 50 km/h des d'un taxi."}], works:[{title:'The Public Theater (1994)',desc:'Sistema tipogràfic que va revolucionar el disseny cultural americà'},{title:'MoMA Identity System',desc:'Modernitat i accessibilitat en equilibri'},{title:'Tiffany & Co.',desc:'Refinament tipogràfic sense ornament'}], lesson_ca:"Una identitat no és un logotip, és un sistema de comportament visual.", lesson_es:"Una identidad no es un logotipo, es un sistema de comportamiento visual.", sources:['Make It Bigger, Paula Scher (2002)','www.pentagram.com'], video_id:'4aSf1HJvKSE', links:[{label:'Pentagram',url:'https://www.pentagram.com/work/paula-scher',icon:'🌐'}], sort_order:9 },
  { slug:'michael-bierut', category_slug:'branding', name:'Michael Bierut', tagline_ca:'El narrador visual del disseny corporatiu', tagline_es:'El narrador visual del diseño corporativo', period:'1957–present', origin:'Cleveland, EUA', portrait_url:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Michael_Bierut.jpg/330px-Michael_Bierut.jpg', bio_ca:"Soci de Pentagram, Bierut entén el disseny com a storytelling visual. Els seus projectes sempre tenen una història darrere que els fa inevitables.", bio_es:"Socio de Pentagram, Bierut entiende el diseño como storytelling visual.", style:['Elegància sense esforç aparent','Concepte narratiu sòlid','Solucions que semblen òbvies en retrospectiva'], techniques:['Investigació cultural profunda','Concepte únic i irresistible com a eix','Presentació narrativa del treball'], principles:[{name:"La idea abans que l'execució",desc:'Cap software resol un concepte feble.'},{name:'El disseny com a diàleg',desc:"El millor treball sorgeix d'entendre a qui parles."},{name:'Confia en el procés',desc:'Amb el problema ben definit, la solució correcta emergeix.'}], works:[{title:'Saks Fifth Avenue (2007)',desc:"Sistema d'identitat amb variacions infinites de luxe"},{title:'New York Times',desc:'Modernització amb autoritat i agilitat digital'},{title:'Hillary for America (2016)',desc:'El logotip polític més analitzat de la història'}], lesson_ca:"Escriu la història del projecte abans d'obrir cap programa.", lesson_es:"Escribe la historia del proyecto antes de abrir ningún programa.", sources:['How to, Michael Bierut (2015)','designobserver.com'], video_id:'MZnBMPVsC3Y', links:[{label:'Pentagram',url:'https://www.pentagram.com/work/michael-bierut',icon:'🌐'}], sort_order:10 },
  { slug:'jonathan-barnbrook', category_slug:'branding', name:'Jonathan Barnbrook', tagline_ca:'El dissenyador com a acte polític i cultural', tagline_es:'El diseñador como acto político y cultural', period:'1966–present', origin:'Luton, R.U.', portrait_url:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/20161128-142503-Jonathan_Barnbrook-m-NP.jpg/330px-20161128-142503-Jonathan_Barnbrook-m-NP.jpg', bio_ca:"Barnbrook demostra que el disseny pot ser un acte de resistència. Les seves tipografies i portades de Bowie demostren que el treball gràfic pot tenir postura moral.", bio_es:"Barnbrook demuestra que el diseño puede ser un acto de resistencia.", style:['Referents històrics recontextualitzats','Detall tipogràfic de precisió extrema','Ironia formal com a eina'], techniques:['Disseny de famílies tipogràfiques completes','Portades com a manifest visual','Capes de significat cultural'], principles:[{name:'El disseny té responsabilitat',desc:'Per a qui i com treballes és part del treball.'},{name:'La història és font',desc:'No citem la història per nostàlgia.'},{name:'La tipografia té política',desc:"Cada tipus té associacions culturals."}], works:[{title:'Portades de David Bowie',desc:'Heathen, Reality i The Next Day com a objectes disseny-art'},{title:'Mason Typeface (1992)',desc:'Formes medievals amb sensibilitat contemporània'},{title:'Virus Fonts',desc:'Catàleg experimental de referència mundial'}], lesson_ca:"Defineix la teva postura abans de la teva estètica.", lesson_es:"Define tu postura antes de tu estética.", sources:['Barnbrook Bible (2007)','barnbrook.net'], video_id:null, links:[{label:'barnbrook.net',url:'https://barnbrook.net',icon:'🌐'}], sort_order:11 },
  { slug:'chip-kidd', category_slug:'branding', name:'Chip Kidd', tagline_ca:'El rei de les portades de llibres', tagline_es:'El rey de las portadas de libros', period:'1964–present', origin:'Pennsylvania, EUA', portrait_url:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/6.28.12ChipKiddByLuigiNovi1.jpg/330px-6.28.12ChipKiddByLuigiNovi1.jpg', bio_ca:"Editor i dissenyador a Knopf, Kidd va convertir la portada de llibre en un art form autònom.", bio_es:"Editor y diseñador en Knopf, Kidd convirtió la portada de libro en un art form autónomo.", style:['Concepte visual que reflecteix el llibre','Misteri com a eina d\'atracció','Minimalisme conceptual d\'alt impacte'], techniques:['Lectura profunda del manuscrit primer','Exploració de metàfores visuals','Disseny com a teaser narratiu'], principles:[{name:'La portada és una promesa',desc:"Ha de transmetre el to en un segon."},{name:'El misteri convida',desc:"Una portada que ho explica tot no convida a obrir-se."},{name:'El concepte primer',desc:'Sense idea sòlida, cap execució brillant salva una portada.'}], works:[{title:'Jurassic Park (1990)',desc:'Silueta de T-Rex: una de les portades més reconoscibles'},{title:'The Cheese Monkeys',desc:'Autoreferència tipogràfica i humor'},{title:'Batman: Death in the Family',desc:"Va elevar l'estàndard visual del còmic"}], lesson_ca:"Llegeix el que dissenyes. La comprensió profunda és l'única font d'una idea visual original.", lesson_es:"Lee lo que diseñas. La comprensión profunda es la única fuente de una idea visual original.", sources:['Chip Kidd: Book One (2005)','www.chipkidd.com'], video_id:'D4iFzWeHFxk', links:[{label:'chipkidd.com',url:'https://www.chipkidd.com',icon:'🌐'},{label:'TED Talk',url:'https://www.ted.com/talks/chip_kidd_designing_books_is_no_laughing_matter_ok_it_is',icon:'🎤'}], sort_order:12 },
  { slug:'rob-janoff', category_slug:'branding', name:'Rob Janoff', tagline_ca:'El creador del símbol tecnològic més valuós', tagline_es:'El creador del símbolo tecnológico más valioso', period:'1952–present', origin:'Califòrnia, EUA', portrait_url:null, bio_ca:"El 1977, amb 25 anys, Janoff va dissenyar la poma mossegada d'Apple.", bio_es:"En 1977, con 25 años, Janoff diseñó la manzana mordida de Apple.", style:['Forma natural simplificada a essència geomètrica','Mossegada com a element funcional','Icona autònoma que funciona sense nom'], techniques:['Observació del món natural com a font','Simplificació progressiva fins a l\'icona','Test d\'escala des de l\'inici'], principles:[{name:"La bona icona no necessita explicació",desc:'Si necessites text perque s\'entengui, el logotip ha fracassat.'},{name:'La imperfecció crea memòria',desc:'La mossegada fa la poma recognoscible a mil·límetres.'},{name:"Dissenya per a l'escala mínima",desc:'Si funciona a 16px, funcionarà en qualsevol cartell.'}], works:[{title:'Apple Logo (1977)',desc:'El símbol corporatiu més reconegut i valuós de la història'},{title:'Apple II Packaging',desc:"Sistema d'identitat inicial"},{title:'Evolució de la poma',desc:"Dels colors a la monocromia"}], lesson_ca:"El millor logotip té una imperfecció calculada que el fa únic.", lesson_es:"El mejor logotipo tiene una imperfección calculada que lo hace único.", sources:['CreativeBits interview (2009)','www.robjanoff.com'], video_id:null, links:[{label:'robjanoff.com',url:'https://www.robjanoff.com',icon:'🌐'}], sort_order:13 },
  { slug:'stefan-sagmeister', category_slug:'contemporanis', name:'Stefan Sagmeister', tagline_ca:"L'artista del disseny conceptual extrem", tagline_es:'El artista del diseño conceptual extremo', period:'1962–present', origin:'Bregenz, Àustria', portrait_url:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Stefan_Sagmeister_in_2025_01.jpg/330px-Stefan_Sagmeister_in_2025_01.jpg', bio_ca:"Sagmeister va explorar els límits entre disseny i art pur. La seva tipografia gravada en el seu propi cos va demostrar que el disseny pot provocar en el sentit més artístic.", bio_es:"Sagmeister exploró los límites entre diseño y arte puro.", style:['Tipografia feta amb objectes físics o cossos','Humor fosc i ironia conceptual','Autobiografia com a material creatiu'], techniques:['Tipografia objectual i corporal','Materials no convencionals','Concepte primer, execució secundària'], principles:[{name:'El procés és el disseny',desc:'La forma en què es fa alguna cosa pot ser més comunicativa que el resultat.'},{name:'El disseny ha de provocar',desc:'Si un treball no genera cap reacció, no ha complert la seva funció.'},{name:'Anys sabàtics són disseny',desc:'La millor creativitat neix de desconnectar sistemàticament.'}], works:[{title:'Lou Reed Set the Twilight Reeling',desc:"Tipografia tallada a la pell, fotografiada com a portada d'àlbum"},{title:'Things I Have Learned',desc:'Llibre-objecte disseny-art-autobiografia'},{title:'The Happy Show',desc:"Exposició sobre la felicitat"}], lesson_ca:"Un cop a l'any, dissenya alguna cosa absolutament personal sense client ni brief.", lesson_es:"Una vez al año, diseña algo absolutamente personal sin cliente ni brief.", sources:['Made You Look (2001)','www.sagmeisterwalsh.com'], video_id:'pTUhkjqJqCQ', links:[{label:'sagmeisterwalsh.com',url:'https://www.sagmeisterwalsh.com',icon:'🌐'}], sort_order:14 },
  { slug:'jessica-walsh', category_slug:'contemporanis', name:'Jessica Walsh', tagline_ca:"L'avanguardista del disseny colorit i surrealista", tagline_es:'La vanguardista del diseño colorido y surrealista', period:'1986–present', origin:'Nova York, EUA', portrait_url:null, bio_ca:"Fundadora de &Walsh, ha construït un dels estudis més influents combinant il·lustració surreal i color explosiu.", bio_es:"Fundadora de &Walsh, ha construido uno de los estudios más influyentes.", style:['Paletes cromàtiques audaces i saturades','Surrealisme visual amb cossos i objectes','Estètica femenina poderosa'], techniques:['Art direction de fotografia surreal','Il·lustració vectorial expressiva','Projectes personals com a carta de presentació'], principles:[{name:"El color és actitud",desc:'Una paleta valent comunica confiança abans de llegir cap paraula.'},{name:'El personal és professional',desc:'Els teus projectes més personals són el teu millor portfolio.'},{name:'El disseny pot sanar',desc:'El treball creatiu té el poder de canviar percepcions culturals.'}], works:[{title:'40 Days of Dating (2013)',desc:'Projecte personal viral que es va convertir en llibre i pel·lícula'},{title:'Ladies Wine & Design',desc:'Iniciativa global que dona suport a dones en el disseny'},{title:'&Walsh Studio',desc:"L'estudi més seguit a Instagram en disseny"}], lesson_ca:"Els projectes personals publicats són el millor portfolio.", lesson_es:"Los proyectos personales publicados son el mejor portfolio.", sources:['andwalsh.com','40 Days of Dating book (2014)'], video_id:'PmWETRQiB58', links:[{label:'andwalsh.com',url:'https://andwalsh.com',icon:'🌐'}], sort_order:15 },
  { slug:'peter-saville', category_slug:'contemporanis', name:'Peter Saville', tagline_ca:'El dissenyador que va donar forma visual a la melancolia', tagline_es:'El diseñador que dio forma visual a la melancolía', period:'1955–present', origin:'Manchester, R.U.', portrait_url:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Peter_Saville_at_i_realize_2009%2C_Turin.jpg/330px-Peter_Saville_at_i_realize_2009%2C_Turin.jpg', bio_ca:"Dissenyador resident de Factory Records, Saville va crear les portades més influents del rock.", bio_es:"Diseñador residente de Factory Records, Saville creó las portadas más influyentes del rock.", style:['Apropiació cultural sofisticada','Paletes fredes i atmosfèriques',"Poètica visual de l'ambigüitat"], techniques:["Apropiació i recontextualització d'imatges",'Tipografia de referència històrica','Composició per sostracció'], principles:[{name:"L'apropiació és creació",desc:'Usar referents existents en nou context genera significats originals.'},{name:'El disseny atmosfèric',desc:"Una portada ha de recrear l'estat emocional."},{name:"L'ambigüitat és riquesa",desc:'Les imatges sense una sola lectura correcta són les que perduren.'}], works:[{title:'Unknown Pleasures – Joy Division (1979)',desc:"La portada més referenciada del rock"},{title:'Blue Monday – New Order (1983)',desc:'Floppy disk: tecnologia i fredor en una sola forma'},{title:"Closer – Joy Division (1980)",desc:"Fotografia funerària que amplifica el drama"}], lesson_ca:"Construeix un arxiu d'imatges que t'emocionen sense saber encara per a què.", lesson_es:"Construye un archivo de imágenes que te emocionan sin saber todavía para qué.", sources:['Designed by Peter Saville (2003)','www.peter-saville.com'], video_id:'5b3V_2_UHV0', links:[{label:'peter-saville.com',url:'https://www.peter-saville.com',icon:'🌐'}], sort_order:16 },
  { slug:'javier-mariscal', category_slug:'hispa', name:'Javier Mariscal', tagline_ca:'El creador del disseny mediterrani pop', tagline_es:'El creador del diseño mediterráneo pop', period:'1950–present', origin:'València, Espanya', portrait_url:'https://upload.wikimedia.org/wikipedia/commons/8/8d/Javier_mariscal.jpg', bio_ca:"Mariscal és el dissenyador espanyol més internacional. En Cobi el va fer universal.", bio_es:"Mariscal es el diseñador español más internacional. Cobi lo hizo universal.", style:['Línia fluïda i expressiva','Colors brillants i càlids mediterranis','Personatges amb personalitat i humor'], techniques:['Esbós com a pensament primari','Color pla amb variacions de to','Línia irregular com a firma personal'], principles:[{name:'El disseny viu',desc:"Un personatge que sembla que respira connecta emocionalment."},{name:"L'espontaneïtat és tècnica",desc:'La línia solta requereix més domini que la línia perfecta.'},{name:'Dissenya amb alegria',desc:"L'estat emocional del dissenyador apareix en el resultat."}], works:[{title:'Cobi (Barcelona 92)',desc:'Mascota olímpica més estimada de la història'},{title:'Bar Cel Ona',desc:'Disseny total: arquitectura, mobiliari i identitat'},{title:'Twipsy (Hannover 2000)',desc:"Personatge digital per a l'Exposició Universal alemanya"}], lesson_ca:"Dissenya personatges amb ànima, no tan sols amb forma.", lesson_es:"Diseña personajes con alma, no solo con forma.", sources:['Designing the New Spain (2009)','www.mariscal.com'], video_id:'V5uQ6VTZLkI', links:[{label:'mariscal.com',url:'https://www.mariscal.com',icon:'🌐'}], sort_order:17 },
  { slug:'alex-trochut', category_slug:'hispa', name:'Alex Trochut', tagline_ca:'El mestre de la tipografia com a escultura', tagline_es:'El maestro de la tipografía como escultura', period:'1981–present', origin:'Barcelona, Espanya', portrait_url:null, bio_ca:"Net del llegendari tipògraf Joan Trochut, Alex ha construït una carrera internacional creant lettering que actua com a il·lustració.", bio_es:"Nieto del legendario tipógrafo Joan Trochut, Alex ha construido una carrera internacional creando lettering.", style:['Tipografia tridimensional i escultòrica','Ornamentació complexa i orgànica','Paletes sofisticades amb daurats i textures'], techniques:['Construcció modular de lletres pròpies','Vectorització manual de precisió extrema','Textures fotogràfiques integrades'], principles:[{name:"L'herència és un trampolí",desc:'Conèixer els mestres del passat dóna vocabulari, no límits.'},{name:'El detall és el treball real',desc:'La distància entre bo i extraordinari viu en els detalls invisibles.'},{name:'La tipografia té volum',desc:'La lletra pot tenir pes, textura, llum i ombra com una escultura.'}], works:[{title:'Nike, Adidas, Rolling Stones',desc:'Lettering de campanya global per a marques de primer nivell'},{title:'The New Yorker, Wired, Time',desc:"Portades tipogràfiques que defineixen l'estàndard actual"},{title:'More is More (Llibre)',desc:'Monografia que resumeix la filosofia maximalista del lettering'}], lesson_ca:"Comença amb més del que necessites. El maximalisme disciplinat és més difícil que el minimalisme.", lesson_es:"Empieza con más de lo que necesitas. El maximalismo disciplinado es más difícil que el minimalismo.", sources:['More is More (2015)','www.alextrochut.com'], video_id:'6ulSBmzXlpI', links:[{label:'alextrochut.com',url:'https://www.alextrochut.com',icon:'🌐'}], sort_order:18 },
  { slug:'cruz-novillo', category_slug:'hispa', name:'Cruz Novillo', tagline_ca:'La llegenda silenciosa del disseny espanyol', tagline_es:'La leyenda silenciosa del diseño español', period:'1936–present', origin:'Conca, Espanya', portrait_url:null, bio_ca:"El dissenyador més influent de la història recent d'Espanya. Els seus logos per a Renfe i Correus continuen vigents dècades després.", bio_es:"El diseñador más influyente de la historia reciente de España.", style:['Geometria constructivista pura','Color com a identitat diferenciadora','Símbol que funciona sense text auxiliar'], techniques:['Anàlisi semiòtica profunda','Construcció geomètrica amb instruments de precisió','Manual d\'identitat exhaustiu'], principles:[{name:'La identitat dura dècades',desc:'Un logotip institucional ha de funcionar 40 anys després.'},{name:'El símbol precedeix el nom',desc:'La forma visual ha de comunicar abans que el cervell processi les lletres.'},{name:'El color és identitat nacional',desc:"El groc de Correus i el vermell de Renfe formen part de la identitat d'Espanya."}], works:[{title:'Renfe',desc:"El sistema d'identitat ferroviària espanyol més reconegut"},{title:"Correus d'Espanya",desc:'El corn postal groc, símbol nacional de generacions'},{title:'Fundació ONCE',desc:'Identitat que comunica solidaritat i modernitat institucional'}], lesson_ca:"El disseny institucional té la màxima responsabilitat: comunica a tot un país.", lesson_es:"El diseño institucional tiene la máxima responsabilidad: comunica a todo un país.", sources:['Cruz Novillo: Identidades Corporativas, DIMAD (2008)','www.cruznovillo.com'], video_id:null, links:[{label:'cruznovillo.com',url:'https://www.cruznovillo.com',icon:'🌐'}], sort_order:19 },
  { slug:'pepe-gimeno', category_slug:'hispa', name:'Pepe Gimeno', tagline_ca:'El mestre del disseny tipogràfic poètic', tagline_es:'El maestro del diseño tipográfico poético', period:'1955–present', origin:'València, Espanya', portrait_url:null, bio_ca:"Un dels tipògrafs espanyols més reconeguts internacionalment, Gimeno explora el territori entre tipografia, disseny i poesia visual.", bio_es:"Uno de los tipógrafos españoles más reconocidos internacionalmente.", style:['Tipografia amb alt contingut emocional','Materialitat com a part integral del concepte','Poètica visual hispanomediterrània'], techniques:['Estudi profund de la història tipogràfica','Composició tipogràfica com a partitura musical','Edició tipogràfica al màxim detall'], principles:[{name:'La tipografia té música',desc:"El ritme i el silenci de les lletres són tan importants com la seva forma."},{name:'El suport és missatge',desc:'El paper i el pes del material comuniquen abans de llegir.'},{name:'Qualitat sobre quantitat',desc:'Un treball perfectament resolt val més que cent de correctes.'}], works:[{title:'La Gràfica Empírica',desc:'Llibre-objecte entre poesia i disseny tipogràfic'},{title:"Museu de les Ciències (València)",desc:"Sistema d'identitat amb alta càrrega cultural valenciana"},{title:'Projectes editorials privats',desc:'Edicions de bibliofília i projectes de referència'}], lesson_ca:"Dedica el mateix temps a triar el paper que a triar la tipografia.", lesson_es:"Dedica el mismo tiempo a elegir el papel que a elegir la tipografía.", sources:['La Gràfica Empírica (2004)','www.pepegimeno.com'], video_id:null, links:[{label:'pepegimeno.com',url:'https://www.pepegimeno.com',icon:'🌐'}], sort_order:20 }
];

exports.handler = async (event) => {
  const headers = { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' };

  if (event.httpMethod === 'OPTIONS') {
    return { statusCode: 200, headers };
  }

  if (event.httpMethod !== 'POST') {
    return { statusCode: 405, headers, body: JSON.stringify({ ok: false, error: 'Method not allowed' }) };
  }

  const adminPw = event.headers['x-admin-password'];
  if (!adminPw || adminPw !== process.env.ADMIN_PASSWORD) {
    return { statusCode: 401, headers, body: JSON.stringify({ ok: false, error: 'Unauthorized' }) };
  }

  let body;
  try { body = JSON.parse(event.body); } catch {
    return { statusCode: 400, headers, body: JSON.stringify({ ok: false, error: 'Invalid JSON' }) };
  }

  const { action, data } = body;
  const db = supabase();

  try {
    switch (action) {

      case 'seed': {
        const rows = SEED.map(d => ({ ...d, is_published: true }));
        const { error } = await db.from('designers').upsert(rows, { onConflict: 'slug' });
        if (error) throw error;
        return { statusCode: 200, headers, body: JSON.stringify({ ok: true, count: rows.length }) };
      }

      case 'get-all-designers': {
        const { data: designers, error } = await db.from('designers').select('*').order('sort_order');
        if (error) throw error;
        return { statusCode: 200, headers, body: JSON.stringify({ ok: true, designers }) };
      }

      case 'save-designer': {
        const { id, ...fields } = data;
        if (id) {
          const { error } = await db.from('designers').update(fields).eq('id', id);
          if (error) throw error;
        } else {
          const { error } = await db.from('designers').insert(fields);
          if (error) throw error;
        }
        return { statusCode: 200, headers, body: JSON.stringify({ ok: true }) };
      }

      case 'delete-designer': {
        const { error } = await db.from('designers').delete().eq('id', data.id);
        if (error) throw error;
        return { statusCode: 200, headers, body: JSON.stringify({ ok: true }) };
      }

      case 'toggle-published': {
        const { data: cur, error: e1 } = await db.from('designers').select('is_published').eq('id', data.id).single();
        if (e1) throw e1;
        const { error: e2 } = await db.from('designers').update({ is_published: !cur.is_published }).eq('id', data.id);
        if (e2) throw e2;
        return { statusCode: 200, headers, body: JSON.stringify({ ok: true, is_published: !cur.is_published }) };
      }

      case 'save-post': {
        const { id, ...fields } = data;
        if (id) {
          const { error } = await db.from('blog_posts').update(fields).eq('id', id);
          if (error) throw error;
        } else {
          const { error } = await db.from('blog_posts').insert(fields);
          if (error) throw error;
        }
        return { statusCode: 200, headers, body: JSON.stringify({ ok: true }) };
      }

      case 'delete-post': {
        const { error } = await db.from('blog_posts').delete().eq('id', data.id);
        if (error) throw error;
        return { statusCode: 200, headers, body: JSON.stringify({ ok: true }) };
      }

      case 'get-all-posts': {
        const { data: posts, error } = await db.from('blog_posts').select('*').order('created_at', { ascending: false });
        if (error) throw error;
        return { statusCode: 200, headers, body: JSON.stringify({ ok: true, posts }) };
      }

      default:
        return { statusCode: 400, headers, body: JSON.stringify({ ok: false, error: 'Unknown action' }) };
    }
  } catch (err) {
    console.error('admin-action error:', err);
    return { statusCode: 500, headers, body: JSON.stringify({ ok: false, error: err.message }) };
  }
};
